### ISSUE TITLE
Is this pkg only for client-side collections?

### ISSUE THREAD

**Issue by lorensr** [jeffmitchel/meteor-local-persist#2]
In my app, I wait for the subscriptions to finish before rendering. This takes a while on 3G, so I'd like to save the contents of the collections in localstorage, and on the next page load, restore from localstorage to `Meteor.Collection`s and immediately render, and then call the subscriptions.

**Comment by jeffmitchel** [comment]
Yes, the intention of this package is to provide client-side persistence only. I'm fairly certain that connecting it to a server persistent collection would not be good for your data integrity, as my code assumes localStorage to be the source of truth and the server will assume it to be Mongo.

**Comment by lorensr** [comment]
Thanks!
