### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by timbrandin** [jeffmitchel/meteor-local-persist#3]
It would be nice to use this package without jQuery, the package is not that Dom traversal dependant so this should be super easy to fix.

**Comment by jeffmitchel** [comment]
I agree. I make some time in the next few days and remove the dependancy.

**Comment by timbrandin** [comment]
Cool, tell me when it's ready for test. :+1:

**Comment by jeffmitchel** [comment]
The package is updated and published. I have not tested it with IE8 yet, but I'm using the same code as both Meteor and jQuery to bind the storage event. I feel confident that it is correct, though I'll feel better once I've verified it on a Windows box.

Thanks for suggesting the change. It was small, but the right way to go.

**Comment by timbrandin** [comment]
LGTM without a flaw!
